### ISSUE TITLE
Type error when creating a reference from one collection to another

### ISSUE THREAD

**Issue by budparr** [static-dev/spike-collections#3]
This is related to the issue I mentioned on [Gitter](https://gitter.im/static-dev/spike?at=58404f53c5bc35217da45bd2). This example steps back from trying to render in the template to where just adding a reference from one collection item in the front matter of another produces an error.

To reproduce.

Install new spike instance with `-t jekyll`. Initially Compiles with no issues. 

Then, add 'authors' collection to app.js, as well as content with three examples and an author sgr template (leave pagination in, because #1). Still no issues.

Change posts collection item to read, in the front matter (This references an item in the authors collection.):

```
author: 'authors-bob'
```

Compiling generates the following error:

```
Error: TypeError: Cannot convert undefined or null to object
```

**Comment by budparr** [comment]
Don't want to muddy the issue, but just to relate back to the original issue I mentioned on Gitter:

What I'm trying to accomplish is this: Given two collections, posts and authors, I'm assigning an author to a post with the pageID. When I loop through a set of posts, I want to then reference the author so I can display copy, etc about them instead of just a slug.

```
// loop through the posts collection
	each(loop='post of _collections.posts')
// the "slug" of the post's author, which should be the same as the pageID, but returns nothing.
	  h1 {{ post.pageID }}
// for each post loop through the staff collection
    each(loop='staff of _collections.staff')
// find only the staff whose pageId match's the post author so we can display all the info about the posts author
	    if(condition="staff.pageId == post.author")
	      h2 {{ staff.title }}
```
I think there's a more efficient way to write this, but I think will illustrate what I'm trying to do.

**Comment by jescalan** [comment]
I'm going to take a look at this today, thanks for the thorough report!

**Comment by budparr** [comment]
Forgot to put the example repo in the initial post:
https://github.com/budparr/2016-12-02-spike-collections-test-v1

**Comment by jescalan** [comment]
Hey sorry for the delay, I just ran this and it's compiling without error. Is there something I need to change here to generate an error?

I just looked back at the original gitter log a second time as well, and this code is working as expected:

```js
return htmlStandards({
      webpack: ctx,
      locals: collections.locals(ctx,
        Object.assign({ pageId: pageId(ctx),...
```

So what's happening here is not that the `collections.locals` function is adding any of the locals passed to each item in the collections. It's actually adding the collections to the locals for normal pages. To add info to collection locals, you can modify options passed into the plugin (like the permalinks option, as you cleverly noted in another issue). The path of each collection item should already be on its data as `path` rather than `pageId`, but if you wanted a transform like `pageId` you could use `permalinks`, soon to be changed to `transform`, to modify this 😁

**Comment by budparr** [comment]
Yeah, it compiles for me too. I don't recall now what i was going through. Makes sense though.
